language: python


matrix:
  include:
    - name: "Xenial pypy 2.7-6.0"
      os: linux
      dist: xenial
      python: pypy2.7-6.0
      install:
        - pip install mpmath sympy testfixtures
      script: ./UnitTesting/run_NRPy_UnitTests.sh pypy

    - name: "Xenial pypy3.5-6.0"
      os: linux
      dist: xenial
      python: pypy3.5-6.0
      script: ./UnitTesting/run_NRPy_UnitTests.sh pypy3

    - name: "Trusty pypy3.5"
      os: linux
      dist: trusty
      python: pypy3.5
      script: ./UnitTesting/run_NRPy_UnitTests.sh pypy3

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: sh          # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      install:
        - pip install mpmath sympy testfixtures
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      env: PYTHONPATH=.:./UnitTesting/:$PYTHONPATH
      script: ./UnitTesting/run_NRPy_UnitTests.sh python

    - name: "Python 3.7 on OS X"
      os: osx
      language: sh
      python: 3.7
      before_script: pip3 install mpmath sympy testfixtures
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3

    # https://docs.travis-ci.com/user/languages/python/
    - name: "Python 3.7 on OS X, xcode 10.2"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_script: pip3 install mpmath sympy testfixtures
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3
      
    - os: linux
      dist: xenial
      python: 2.7
      before_script: pip install testfixtures
      script: ./UnitTesting/run_NRPy_UnitTests.sh python

    - os: linux
      dist: xenial
      python: 3.4
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3

    # According to https://github.com/tornadoweb/tornado/blob/master/.travis.yml:
    #  3.5.2 is interesting because it's the version in ubuntu 16.04, and due to python's
    # "provisional feature" rules there are significant differences between patch
    # versions for asyncio and typing.
    - os: linux
      dist: xenial
      python: 3.5.2
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3

    - os: linux
      dist: xenial
      python: 3.7
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3

    - os: linux
      dist: xenial
      python: 3.8-dev
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3

    - os: linux
      dist: xenial
      python: nightly
      script: ./UnitTesting/run_NRPy_UnitTests.sh python3

