# from https://docs.travis-ci.com/user/languages/python/
language: python
python:
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install sympy
  - pip install coverage
  - pip install codecov
# We generally don't need to install matplotlib for the test.
#  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run BSSN/test/BSSN_exact_ID_tests.py
  - bash <(curl -s https://codecov.io/bash) -cF python
  - coverage run BSSN/test/BSSN_ADM_Test.py
  - bash <(curl -s https://codecov.io/bash) -cF python

# After completion, push results to codecov
after_success:
  - codecov
