# from https://docs.travis-ci.com/user/languages/python/
language: python
python:
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install sympy
#  - pip install coverage
#  - pip install codecov
# We generally don't need to install matplotlib for the test.
#  - pip install -r requirements.txt
# command to run tests
before_script: BSSN/test/run_BSSN_tests.sh

script: travis_wait 30 pypy BSSN/test/BSSN_Globals_Tests.py
# After completion, push results to codecov
#after_success:
#  - codecov
