language: python

matrix:
  include:
    - os: linux
      python: 3.5.2
      script: ./UnitTesting/run_NRPy_UnitTests.sh

    - os: linux
      python: 3.7
      script: ./UnitTesting/run_NRPy_UnitTests.sh