language: python

script: ./UnitTesting/run_NRPy_UnitTests.sh

matrix:
  include:
    - os: osx
      language: sh
#      osx_image: xcode9.2
      python: 3.7
      before_script: pip install mpmath sympy testfixtures

    # https://docs.travis-ci.com/user/languages/python/
    - os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: alias python=python3
      before_script: pip3 install mpmath sympy testfixtures
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_script: pip3 install mpmath sympy testfixtures
      
    ### - os: linux
    ###   dist: xenial
    ###   python: 2.7
    ###   before_script: pip install testfixtures

    ### - os: linux
    ###   dist: xenial
    ###   python: 3.4

    ### # According to https://github.com/tornadoweb/tornado/blob/master/.travis.yml:
    ### #  3.5.2 is interesting because it's the version in ubuntu 16.04, and due to python's
    ### # "provisional feature" rules there are significant differences between patch
    ### # versions for asyncio and typing.
    ### - os: linux
    ###   dist: xenial
    ###   python: 3.5.2

    ### - os: linux
    ###   dist: xenial
    ###   python: 3.7

    ### - os: linux
    ###   dist: xenial
    ###   python: 3.8-dev

    ### - os: linux
    ###   dist: xenial
    ###   python: nightly

    ### - os: linux
    ###   dist: xenial
    ###   python: pypy2.7-6.0

    ### - os: linux
    ###   dist: xenial
    ###   python: pypy3.5-6.0

    ### - os: linux
    ###   dist: xenial
    ###   python: pypy3.5-6.0
